url: ""
baseurl: "" # the subpath of your site, e.g. /blog/

# Site settings
title: Mobile Refresh
email: mmegazar@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  GDG Wellington, together with Cocoaheads Wellington is proud to bring you Mobile Refresh 2016. Our one-day conference is aimed at mobile technology enthusiasts who are interested in a quick update on the latest developments announced at Google I/O and WWDC.
twitter_username: GDGWellington

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/GDGWellington
  - title: slack
    url: http://slack.gdg.nz/

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
